### ISSUE TITLE
FailOnError only to Trigger on Error

### ISSUE THREAD

**Issue by joezimjs** [danielhusar/gulp-stylint#16]
I think that `failOnError` should only cause an error if there are errors. Warnings should not cause the fail. Otherwise I don't see the purpose of having 2 warning levels.

**Comment by SimenB** [comment]
As 2 or 3 separate options, or just change `failOnError`? We could probably look at `maxErrors` and `maxWarnings` in the config of stylint as well...
@danielhusar Thoughts?

**Comment by joezimjs** [comment]
Just change failOnError. gulp-eslint has a failOnError method that will make sure warnings are still presented but will not fail unless it encounters an error.

**Comment by SimenB** [comment]
Ah, like gulp-jshint and gulp-csslint. That could be done pretty easily. Pretty big change to allow multiple pipings into the module, though. Any objections to that @danielhusar? I can implement it, just want go-ahead in case you're not interested :smile: 
Would require a version 2 of course

**Comment by danielhusar** [comment]
Hey looks good to me :)

**Comment by danielhusar** [comment]
Available in `2.0.0`

**Comment by SimenB** [comment]
@joezimjs Does 3.0 provide what you want? https://github.com/danielhusar/gulp-stylint#fail-reporter

**Comment by joezimjs** [comment]
@SimenB Looks good from the documentation. I'll have to give it a test when I get time, but I assume it works, otherwise you wouldn't have published it :smile:

**Comment by SimenB** [comment]
It works for me at work :smile:

**Comment by joezimjs** [comment]
Works for me too :smiley:

**Comment by SimenB** [comment]
Sweet :+1:
