### ISSUE TITLE
Custom reporter as option

### ISSUE THREAD

**Issue by yoyurec** [danielhusar/gulp-stylint#17]
Atom editor stylint plugin stops to work when i set `stylint-stylish` in `.stylintrc`
So i should set it in gulp task programmatically...

```
gulp.task('ld-stylus-lint', function () {
    return gulp
        .src('*.styl')
        .pipe(stylint({
            config: {reporter: 'stylint-stylish'},
            failOnError: true
        }));
});
```

but it doesn't output warnings (files has them), without this config default reporter works:

![](https://cloud.githubusercontent.com/assets/137919/9033668/ecf43cb8-39d1-11e5-98ed-c3993e1bd1d1.png)

version - `1.1.10`

**Comment by SimenB** [comment]
@yoyurec Could you give it a try? Just install from npm (`"gulp-stylint": "danielhusar/gulp-stylint"` in `dependencies`)

**Comment by yoyurec** [comment]
```
        .pipe(stylint({
            config: '.stylintrc',
            reporter: {
              reporter: 'stylint-stylish',
              reporterOptions: {
                verbose: true
              }
            },
            failOnError: true
        }));
```

works perfect!!! :dancers: :+1:
