### ISSUE TITLE
Tests fail on latest stylint

### ISSUE THREAD

**Issue by SimenB** [danielhusar/gulp-stylint#19]
Worked fine on `~1.0.0`, but broken on `1.1.0`. I haven't looked into why, and it's way past my bedtime... I'll take a look tomorrow, hopefully, unless someone else solves it

//cc @danielhusar @rossPatton

**Comment by danielhusar** [comment]
Fixed with https://github.com/danielhusar/gulp-stylint/commit/e968e5e867e2d145774082839d4902a593f6fae7

The default spaces intentation has changed.
