### ISSUE TITLE
fix check leading zero

### ISSUE THREAD

**Issue by erguotou520** [danielhusar/gulp-stylint#22]
Refer [fix check leading zero](https://github.com/rossPatton/stylint/pull/253)
Please update when `stylint` updated.

**Comment by SimenB** [comment]
@erguotou520 What do you want this plugin to do? As long as whatever needs updating on stylint's end doesn't bump it to 2.0, you'll get the update by just running `npm update`.

**Comment by erguotou520** [comment]
Sorry for forget to check the dependence `"stylint": "^1.0.11"`
