### ISSUE TITLE
Fix path of stylint

### ISSUE THREAD

**Issue by sodoku** [danielhusar/gulp-stylint#3]
The path of stylint is set to `node_modules/gulp-stylint/node_modules/stylint/bin/stylint` (https://github.com/danielhusar/gulp-stylint/blob/master/index.js#L6), which works if you only install `gulp-stylint`.
But if you have installed `stylint` allready, its path is `node_modules/stylint/bin/stylint` and the plugin does not find the binary.

**Comment by danielhusar** [comment]
Good catch, I will fix that.

**Comment by danielhusar** [comment]
Should be fine now in `1.1.1`.
https://github.com/danielhusar/gulp-stylint/commit/02b1f8808db64cc0784332a798165c13321810c8

**Comment by sodoku** [comment]
Awesome. Thanks for the fast fix!
