### ISSUE TITLE
Watch: task runs on change but reports only on first run

### ISSUE THREAD

**Issue by fdeneux** [danielhusar/gulp-stylint#30]
As the title says.

**Comment by SimenB** [comment]
Would you be able to put together a repo showing this? Or even better, provide a PR (just a failing test would be fantastic 😄)?

**Comment by fdeneux** [comment]
edit: I'm sorry @SimenB but I was unable to reproduce the issue. No idea why it would not report before.

**Comment by SimenB** [comment]
Ok, that's fine! Don't hesitate to reopen if you can reproduce 😄
