### ISSUE TITLE
Migrate away from using the deprecated gulp-util

### ISSUE THREAD

**Issue by asghol** [danielhusar/gulp-stylint#34]
The following guide can be followed to migrate: [https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5](https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5)

**Comment by karstens** [comment]
Is this PR gonna be merged anytime soon ? https://github.com/danielhusar/gulp-stylint/pull/35

**Comment by danielhusar** [comment]
Merged and released `4.0.2`. Thanks!

**Comment by karstens** [comment]
Thank you !

**Comment by karstens** [comment]
Just adding the reference to the issue in gulp-util https://github.com/gulpjs/gulp-util/issues/143
